# Longitudinal control

## Vertical Speed

In [1]:
from scipy import signal
import numpy as np

In [2]:
A = np.array([[-0.01, 0.1, 0, -32.2], 
              [-0.40, -0.8, 180, 0],
              [0, -0.003, -0.5, 0],
              [0, 0, 1, 0]])

B = np.array([[0], [-10], [-2.8], [0]])

C = np.array([[0, 0, 0, 1]])

D = np.array([[0]])

sys = signal.StateSpace(A, B, C, D)
print(sys.poles)

[-0.66663372+0.73510829j -0.66663372-0.73510829j  0.01163372+0.19774139j
  0.01163372-0.19774139j]


/opt/homebrew/lib/python3.11/site-packages/scipy/signal/_filter_design.py:1746: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  warnings.warn("Badly conditioned filter coefficients (numerator): the "


In [7]:
zeta_sp = 0.6
w_n_sp = 2.0
zeta_ph = 0.05
w_n_ph = 0.1

sys_2 = signal.ZerosPolesGain([], [-zeta_sp+w_n_sp*1j, -zeta_sp-w_n_sp*1j, -zeta_ph+w_n_ph*1j, -zeta_ph-w_n_ph*1j], 1)
print(sys_2.poles)
print(sys_2.to_ss())

[-0.6 +2.j  -0.6 -2.j  -0.05+0.1j -0.05-0.1j]
StateSpaceContinuous(
array([[-1.3   , -4.4925, -0.451 , -0.0545],
       [ 1.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  1.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  1.    ,  0.    ]]),
array([[1.],
       [0.],
       [0.],
       [0.]]),
array([[0., 0., 0., 1.]]),
array([[0.]]),
dt: None
)
